version: "3"

services:
  api:
    container_name: api
    # restart: always
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=production
    command: "gunicorn -b :5000 wsgi"

  frontend:
    container_name: frontend
    # restart: always
    build:
      context: ./frontend
      dockerfile: 'Dockerfile'
    depends_on:
      - api
    command: nginx -g 'daemon off';

  nginx-rev-proxy:
    container_name: nginx-rev-proxy
    # restart: always
    build:
      context: ./nginx
      dockerfile: 'Dockerfile'
    depends_on:
      - api
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off';
