version: "3"

services:
  api:
    container_name: api-dev
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=development
    volumes:
      - ./api:/ipcalc/api:z
    ports:
      - 5000:5000
    command: python run.py

  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./frontend:/ipcalc/frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    command: npm start
