version: "3"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=development
    hostname: api
    volumes:
      - ./api:/ipcalc/api
    command: bash -c 'gunicorn -b :5000 wsgi';

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    restart: always
    depends_on:
      - api
    ports:
      - 80:80
      - 5000:5001
    command: nginx -g 'daemon off';
