version: '3'

services:
  flask:
    build: ./api
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=development
    command: ["python", "run.py"]
    volumes:
      - ./api:/ipcalc/api
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/ipcalc/frontend
      - node-modules:/ipcalc/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
