version: "3"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=development
    volumes:
      - ./api:/ipcalc/api:z
    ports:
      - 5000:5000
    command: python run.py

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: 'Dockerfile.dev'
    volumes:
      - ./frontend:/ipcalc/frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    command: npm start

  nginx-rev-proxy:
    container_name: nginx-rev-proxy
    # restart: always
    build:
      context: ./nginx
      dockerfile: 'Dockerfile'
    depends_on:
      - api
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
    ports:
      - 80:80
      - 443:443
    command: nginx -g 'daemon off';
