version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    restart: always
    ports:
      - 80:80
    command: nginx -g 'daemon off';
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=development
    hostname: api
    ports:
       - 5000:5000
    volumes:
      - ./api:/ipcalc/api
    command: bash -c 'gunicorn -b :5000 wsgi';
