version: "3"

services:
  api:
    container_name: api
    # restart: always
    build:
      context: ./api
      dockerfile: 'Dockerfile'
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=production
    ports:
      - '5000:5000'
    command: "gunicorn -b :5000 wsgi"

  frontend:
    container_name: frontend
    # restart: always
    build:
      context: ./frontend
      dockerfile: 'Dockerfile'
    depends_on:
      - api
    ports:
      - '8000:80'
    command: nginx -g 'daemon off';
  #
  # nginx-rev-proxy:
  #   container_name: nginx-rev-proxy
  #   # restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: 'Dockerfile'
  #   depends_on:
  #     - api
  #     - frontend
  #   ports:
  #     - 8001:80
  #     - 5000:5000
  #   command: nginx -g 'daemon off';
